version: '3.9'
services:
  app:
    container_name: nestjs_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
    depends_on:
      - db

  db:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
